[week7] 회원 삭제 soft delete로 변경
CodeSoom/spring-week7-assignment-1 pull request #52
Opened 2022-05-06 06:54 UTC by SUBIN606

강의 내용 대로 회원 삭제에 soft delete 방식을 적용합니다.

2022-05-06 12:17 UTC, johngrib reviewed
PR 타이틀에서 `[week7]`은 없어도 괜찮을 것 같아요. 코드숨이 아니라 회사라고 생각하고 작업한다고 상상해보면 도움이 될 거에요.

![image](https://user-images.githubusercontent.com/1855714/167129629-eaa72420-2c74-477a-907d-b70b86855994.png)

2022-05-06 12:26 UTC, johngrib requested changes
`getDeleted` 메소드의 이름이 `isDeleted`이면 더 좋을 것 같습니다.

2022-05-06 12:26 UTC, johngrib commented on app/src/test/java/com/codesoom/assignment/domain/users/UserTest.java
> +        @DisplayName("deleted 필드를 true로 변경한다.")
`deleted` 필드는 private 이므로 이 테스트의 주요 인물로 등장하지 않아도 괜찮습니다. 한편 `destory` 메소드를 실행한 환경은 context라고 생각해보면, 이 테스트는 `getDeleted`가 주인공인 테스트가 되어도 괜찮을 거에요.

2022-05-06 12:26 UTC, johngrib commented on app/src/main/java/com/codesoom/assignment/domain/users/User.java
> +    }
이렇게 설명해도 괜찮겠죠.
`이 회원을 삭제 상태로 변경하고, 변경된 회원을 리턴합니다.`

2022-05-06 12:28 UTC, johngrib commented
코드 리뷰의 결과로 change request를 남겨 보았습니다. change request를 남기면 이렇게 빨간 색 아이콘과 함께 리뷰어의 요구를 확인할 수 있어요. 사실 이 메소드는 지금도 괜찮지만, 이 PR에 추가 작업을 하는 연습을 위해 남겨 보았습니다.

![image](https://user-images.githubusercontent.com/1855714/167131095-fa03d419-437d-49b5-a900-fb521e3277d1.png)

2022-05-07 10:56 UTC, SUBIN606 commented on app/src/test/java/com/codesoom/assignment/domain/users/UserTest.java
> +        @DisplayName("deleted 필드를 true로 변경한다.")
고쳐보긴 했는데 제대로 이해한 건지 잘 모르겠네요..!

2022-05-07 13:08 UTC, johngrib reviewed
디테일한 설명이 좋습니다. 다만 주제 하나를 콕 집어서 강조하는 것도 좋을 것 같아요. 이 작업의 주인공은 `getDeleted`를 `isDeleted`로 바꾼 것이고, 나머지 작업들은 메소드 이름 변경의 서브 작업들이라 할 수 있겠죠. 그러니 커밋 메시지도 주인공 작업을 명확히 드러내는 것이었다면 더 좋았을 거에요.

![image](https://user-images.githubusercontent.com/1855714/167255784-b0e913d1-b545-420a-8b4f-af18d516094e.png)

2022-05-07 13:09 UTC, johngrib approved these changes
좀 더 읽기 좋은 테스트 코드가 되었습니다. 고생하셨습니다!

2022-05-07 13:09 UTC, merged